library(RJDBC)
print("RJDBC library loaded successfull")
library(doParallel)
print("doParallel library loaded successfull")
library(foreach)
print("foreach library loaded successfull")
library(plyr)
print("plyr library loaded successfull")
library(RAmazonS3)
print("RAmazonS3 library loaded successfull")
library(data.table)
print("data.table library loaded successfull")
